name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: install dependencies
        run: sudo apt-get install -y discount make gcc
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cd repo
        run: cd ${{ github.workspace }}
      - name: build
        run: |
            cd bin
            make
            python make-redirects.py
      - name: add custom domain
        run: echo "lipu-sona.pona.la" > public/CNAME
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}/public"
